## Your name - Armen Mkrtumyan

### Exercise 0 (1 point) - Import the numpy package. 

In [1]:
import numpy as np

### Exercise 1 (9 points) 
### a. Create a 3x3 matrix with consecutive values ranging from 0 to 8 (i.e. 0, 1, 2, 3, 4, 5, 6, 7, 8) filled in the matrix row by row. 
### b. Create a 3x3x3 array filled with random integer values from 10 to 20 both inclusive.
### c. Create an array 10x10x3 with all elements set to one. Reshape it so that the size of the second dimension equals 150.

In [2]:
# Solution 

#1
print(np.arange(0,9).reshape(3,3), '\n','\n')

[[0 1 2]
 [3 4 5]
 [6 7 8]] 
 



In [3]:
#2
print(np.random.randint(10,21, (3,3,3)))

[[[13 16 11]
  [15 10 16]
  [14 14 15]]

 [[11 15 12]
  [17 10 19]
  [17 16 12]]

 [[14 10 14]
  [13 17 18]
  [11 14 10]]]


In [4]:
#3

my_arr = np.ones((10,10,3))
my_arr_reshaped = my_arr.reshape((1,150,2))
print(my_arr_reshaped)

[[[1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]
  [1. 1.]


### Exercise 2. (12 points) Given the *arr_1* numpy array, 
### a. get a new array that will include only odd numbers from the *arr*,
### b. get a new array where all odd numbers from the original array is replaced with -1. 
### c. get a new array from the original array where the maximum value of the array is replaced by 0. 
### d. filter the original array and get a new array that contains only values greater than 10 and smaller than 20. You can use "&" and have one condition or do it with two separate conditions. 

In [5]:
# Solution 
arr_1 = np.array([17, 30, 29, 38, 16, 7, 33, 24, 33, 21, 31, 20, 25, 6, 44, 16, 46, 16, 34, 8])

### a

In [6]:
odd_arr = arr_1[arr_1 % 2 != 0]
print(odd_arr)

[17 29  7 33 33 21 31 25]


### b

In [7]:
replaced_arr = arr_1.copy()
replaced_arr[arr_1 % 2 != 0] = -1
print(replaced_arr)

[-1 30 -1 38 16 -1 -1 24 -1 -1 -1 20 -1  6 44 16 46 16 34  8]


### c

In [8]:
new_arr = arr_1.copy()
index_of_max_element = np.where(arr_1 == arr_1.max())[0][0]
new_arr[index_of_max_element] = 0
print(new_arr)

[17 30 29 38 16  7 33 24 33 21 31 20 25  6 44 16  0 16 34  8]


### d

In [9]:
arr_1[np.logical_and(arr_1 > 10,arr_1 < 20)]

array([17, 16, 16, 16])

### Exercise 3. (8 points) Write a function, that gets as an input an integer *n*, and returns a $ nxn $ 2-d array with zeros on the border and 1 everywhere else.

#### Example: n = 3, output 
0 0 0 <br>
0 1 0 <br>
0 0 0 <br>

In [10]:
# Solution 
try:
    n = int(input("Please input an integer n "))
    if(n < 0):
        raise ValueError
    my_arr = np.zeros((n,n))
    my_arr[1:-1, 1:-1] = 1
    print(my_arr)
except ValueError:
    print("invalid input")

Please input an integer n 4
[[0. 0. 0. 0.]
 [0. 1. 1. 0.]
 [0. 1. 1. 0.]
 [0. 0. 0. 0.]]


### Exercise 4. (8 points) Write a function, that gets as an input 2d numpy array of np.int32 values, and adds a border filled with 0s around the array (from all sides), and returns the array. Check in your function the type and dimension of the array and raise an exception if they do not satisfy the problem definition. (Hint: np.pad)

In [12]:
#### Solution 

try:
    columns = int(input("Please input the number of columns of the array: "))
    if(columns < 0):
        raise ValueError
                    
    try:
        rows = int(input("Please input the number of rows of the array: "))
        if(rows < 0 or (rows == 0 and columns == 0)):
            raise ValueError
        array = np.ones((rows, columns), dtype = np.int32)
        for i in range(0, columns):
            for k in range(0, rows):
                while(True):
                    try:
                        array[i, k] = int(input("Input the element ({},{})".format(i,k)))
                        break
                    except ValueError:
                        print("Array must be filled with int values only")
        my_array = np.pad(array,((1,1),(1,1)), 'constant')
        print(m9y_array)
    except ValueError:
        print("invalid input")
except ValueError:
    print("invalid input")


Please input the number of columns of the array: 4
Please input the number of rows of the array: 4
Input the element (0,0)6, 7
Array must be filled with int values only
Input the element (0,0)6 7
Array must be filled with int values only
Input the element (0,0)5
Input the element (0,1)8
Input the element (0,2)9
Input the element (0,3)9
Input the element (1,0)9
Input the element (1,1)9
Input the element (1,2)9
Input the element (1,3)9
Input the element (2,0)9
Input the element (2,1)9
Input the element (2,2)9
Input the element (2,3)9
Input the element (3,0)9
Input the element (3,1)9
Input the element (3,2)9
Input the element (3,3)9
[[0 0 0 0 0 0]
 [0 5 8 9 9 0]
 [0 9 9 9 9 0]
 [0 9 9 9 9 0]
 [0 9 9 9 9 0]
 [0 0 0 0 0 0]]


In [ ]:
my_array #to check the dtype

### Exercise 5. (8 points) Create a function that returns eight-by-eight matrix filled with a checkerboard (black and white being 0s and 1s) pattern.

In [21]:
np.tile([[0,1],[1,0]], (4,4))

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

### Exercise 6. (8 points) Let x be a numpy array [0, 0, 0, 1, 2, 0, 3, 0, 2, 1, 0]
### a. remove all zeros from the array,
### b. remove the leading the trailing zeros. (hint: numpy has a function that can easily do this, search for it)

In [ ]:
# Solution

x = np.array([0, 0, 0, 1, 2, 0, 3, 0, 2, 1, 0])

### a

In [ ]:
print(x[x != 0])

### b

In [ ]:
np.trim_zeros(x)

### Exercise 7. (8 points) Create a simulation of dice rolling, 1000 times. That is create a numpy array with 1000 random integers from 1 to 6. Then count how many 6s were rolled and divide this number to 1000. Is the number close to 1/6 ? 

In [ ]:
dice_rolls = np.random.randint(1,7, size = (1,1000))
print("My calculation: ", (dice_rolls[dice_rolls == 6].size)/1000)
print("1/6 is: ", 1/6)
print("Yes it is close")

### Exercise 8. (15 points) Given a numpy array, get 
### a. the largest value of an array, 
### b. the second largest value of an array
### c. the unique elements from the array (hint: np.unique)
### d. find 3 most frequent values in the array (hint: explore arguments of the np.unique)
### e. find the indices of elements that are zero (hint: np.where)

In [ ]:
# Solution
arr_2 = np.array([ 2, 12, 19, 12, 15, 10,  4,  2, 0,  9,  9,  9,  2, 19,  3, 0,  7, 13, 15, 11,  2, 13, 0])

### a

In [ ]:
arr_2.max()

### b

In [ ]:
arr_2[~ (arr_2 == arr_2.max())].max()

### c

In [ ]:
np.unique(arr_2)

### d

In [ ]:
arr_element, arr_max = np.unique(arr_2, return_counts=True)

In [ ]:
arr_element

In [ ]:
arr_max

In [ ]:
frequents = []

## Since there was an issue with the quantity of frequent elemens (length was being more than 3, I decided to use loops) joined with numpy arrays

In [11]:
while(len(frequents) != 3):
    for i in range(0, len(arr_max)):
        if(arr_max[i] == arr_max.max()):
            frequents.append(arr_element[i])
            if(len(frequents) == 3):
                break
    arr_element = arr_element[~(arr_max == arr_max.max())]
    arr_max = arr_max[~(arr_max == arr_max.max())]

NameError: name 'frequents' is not defined

In [ ]:
frequents

### e

### Exercise 9. (8 points) Given a 2d numpy array.
### a. switch 0th and 1st rows.
### b. switch 2nd and 3rd columns.

In [ ]:
# Solution 
arr_3 = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]])

## a

In [ ]:
arr_3

In [ ]:
arr_3[[0,1]] = arr_3[[1,0]]

In [ ]:
arr_3

### b

In [ ]:
arr_3[[2,3]] = arr_3[[3,2]]

In [ ]:
arr_3

### Exercise 10. (15 points) Consider a random 10x2 matrix representing cartesian coordinates (first column are x-s, second column are y-s), convert them to polar coordinates.
$$
(r, \theta) = (\sqrt{x^2 + y^2}, \tan^{-1} \big( \frac{y}{x} \big) )
$$

### You should obtain again 10x2 matrix, where the first column will be $r$, second $\theta$. Write a function that does this, and then test your function on a matrix full of random numbers. (hint: be careful whether you need np.arctan or np.arctan2.)

In [ ]:
def get_values(row):
    r = np.sqrt(row[0]**2 + row[1]**2) 
    theta = np.arctan2(row[1], row[0])
    return(np.array([r, theta]))
def polar_converter(matrix):
    new_matrix = np.empty(matrix.shape)
    for i in range(0, len(matrix)):
        row = get_values(matrix[i])
        new_matrix[i] = row
    return(new_matrix)
matrix = np.random.randint((10,10), size=(10,2))
new_matrix = polar_converter(matrix)
print(new_matrix)